name: Auto Archiving Closed issues

on:
  repository_dispatch:
    types:
      - dispatch_from_all_issues  
      - dispatch_from_internal_issues  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run some command
      env:
        CLIENT_PAYLOAD : ${{ toJson(github.event.client_payload) }}
      run: |
        echo "Target workflow triggered!"
        echo $CLIENT_PAYLOAD