name: Auto Archiving Closed issues

on:
  repository_dispatch:
    types:
      - dispatch_from_all_issues  
      - dispatch_from_internal_issues  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: Handle dispatch_from_all_issues
    #   if: ${{ github.event.action.determine_type.outputs.dispatch_type == 'dispatch_from_all_issues' }}
    #   run: |
    #     echo "Handling dispatch_from_all_issues"
    #     # Add your logic here
    #     ${{ github.event.}}

    # - name: Handle dispatch_from_internal_issues
    #   if: ${{ github.event.action.determine_type.outputs.dispatch_type == 'dispatch_from_internal_issues' }}
    #   run: |
    #     echo "Handling dispatch_from_internal_issues"

    - name: Run some command
      env:
        CLIENT_PAYLOAD : ${{ toJson(github.event.client_payload) }}
        ACTION_NAME : ${{ github.event.action }}
      run: |
        echo "Target workflow triggered!"
        # echo "${{ toJson(github.event.sender) }}"
        echo "${{ toJson(github.event_path) }}"
        echo "${{ toJson(github.event_name) }}"
        echo "${{ toJson(github.event.action) }}"
        echo $CLIENT_PAYLOAD