name: Auto Archiving Closed issues

on:
  repository_dispatch:
    types:
      - dispatch_from_all_issues  
      - dispatch_from_internal_issues  

# 这玩意就是控制并发的，流水线运行后会自动加锁
# 在一个组的流水线任务只能有一个在运行，其他流水线任务会被pedding
# 文档：https://docs.github.com/zh/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
concurrency:
  group: archiving-group

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Run some command
      env:
        CLIENT_PAYLOAD : ${{ toJson(github.event.client_payload) }}
        ACTION_NAME : ${{ github.event.action }}
      run: |
        cd ./
        python ./auto_archiving/scripts/main.py -c ./auto_archiving/configs/config.json
      
    - name: Add and commit changes
      uses: actions/checkout@v4
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ./修改归档.md
        git commit -m "Closed issue#${{ github.event.client_payload.issue_id}}"
        git push origin main
      run: |
        